### ISSUE TITLE
fathom xml in wav

### ISSUE THREAD

**Issue by Alex-Longard** [michaelgregorius/fathom-wavetable-converter#1]
Hello Michael,
do you can write in your script functions for convert Fathom xml wavetables in wave file?

**Comment by michaelgregorius** [comment]
@Alex-Longard I have implemented the functionality to convert Fathom XML files to wav files with commit dc91578722fe11df44d644b496b401da2397c3da.

Currently it can only convert single files provided on the command line but that's something that can be worked around with a bash script. Please refer to the README for more details on how to use this mode.

**Comment by Alex-Longard** [comment]
Hello Michael!
Big thanks!
